### ISSUE TITLE
Project Enhancements v3.0: Relicensing and Release open-source automated CLI build scripts.

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/raspberry-pi-cross-compilers#32]
### From Author
Hello fellow developers.

I'm proud to announce that this project is now moving into the next phase of Free and open-source software. Since it initial release on Sourceforge, it has now over 7000 downloads from all across the globe within the short 1-year span and still growing fast. So I've decided to open-source all build-scripts(used to compile these toolchains easily) that I've developed over these years and turn this project into an Automated CI GCC compiling/building/deploying pipeline so that binaries are built automatically from the latest GCC source with ensured transparency at its every stage. Plus, This project is now being relicensed to GNU's General Public License(GPL) v3 which guarantees end users the freedom to run, study, share, and modify the software while ensuring that source is disclosed to community. I hope this will help everyone and take this project to greater heights.

Regards
@abhiTronix 

### Brief History:

This is a non-profit project that was initially originated for hosting precompiled GCC Toolchains Repository for raspberry pi but later these precompiled binaries were moved to Sourceforge, due to limited space available. These toolchains were developed as a part of my various research college projects but later I made them open-sourced for the public interest.

### Roadmap
The project will move into the next phase in three easy steps which will be fulfilled in the next few days. These steps are as following:

- [x] **Step -1:** Update project License to GNU's General Public License(GPL) v3 **(Done: #33)**
- [x] **Step-2:** Release various build scripts and Setup continuous integration so that binaries are built automatically from the latest GCC source and finally auto-deploy compiled binaries to Sourceforge
- [x] **Step-3:**  Fix all related bugs and Update docs.

### Idea Credit:

**@jcelerier**
